### PR TITLE
resolve dfs in sophomorix-quota

### PR DESCRIPTION
**Pull request by PLanB2008**
Allow setting Quota on fileserver by resolving DFS in sophomorix

### CODE REVIEW

**Comment by PLanB2008** [comment]
I extended the PR. -mNT1 shouldn't be used at all and wont work with ubuntu 20.04 alltogether.

**Comment by PLanB2008** [comment]
I extended the PR for following:

- dont use -mNT1 at all (does not work with higher fileservers running eg ubuntu20.04)
- fixed determining of homepath in sophomorix-transfer

Please merge :)

**Comment by jeffbeck** [comment]
When issuing the following command in my test scripts:

/usr/bin/smbclient --debuglevel=0 -U administrator%'******' //linuxmuster.local/bsz   -c 'stat "teachers/wu72/transfer/77.txt"; exit;'

I get the following error using your code:

Server doesn't support UNIX CIFS calls

Did you reconfigure the samba server to make your changes work?

**Comment by kiarn** [comment]
Actual samba version does not support posix commands anymore, it's not possible to use `stat`, you should use `allinfo`

This pull request should be reopened and merge, because actually all users do have to do this changes manually on their servers in order to use linuxmuster.net.

Please see : https://ask.linuxmuster.net/t/lmn-7-2-testing/9732/211

**Pull request merged**
